AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: v1.1 Deployment of Frontend NVA

Parameters:
  AlmaSruHost:
    Type: String
    Description: AWS::SSM::Parameter::Value<String>
    Default: AlmaSruHost
  ApplicationDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Description: |
      Base part of the domain the stack and components will be deployed to. Must be covered by the certificate.
      Could be somethoing like .test.aws.unit.no or np-733.test.aws.no.
      Used to calculate the other addresses in the deployment
    Default: ApplicationDomain
  ApplicationDomainCertificateArn:
    Type : AWS::SSM::Parameter::Value<String>
    Description: ARN  of certificate to assign to the assosiated Domain
    Default: ApplicationDomainCertificateArn
  BackendApiUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: BackendApiUrl
  CognitoAuthenticationDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CognitoAuthenticationDomain
  CognitoIdentityPoolId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CognitoIdentityPoolId
  CognitoUserPoolAppClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CognitoUserPoolAppClientId
  CognitoUserPoolId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CognitoUserPoolId

  OrcidBaseUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Address to ORCID services
    Default: OrcidBaseUrl
  OrcidClientID:
    Type: String
    Description: Clientid for ORCID
    NoEcho: true
    Default: '{{resolve:secretsmanager:OrcidClientID:SecretString}}'
  OrcidClientSecret:
    Type: String
    Description: Secret to authenticate for ORCID
    NoEcho: true
    Default: '{{resolve:secretsmanager:OrcidClientSecret:SecretString}}'
  OrcidRedirectUri:
    Type : AWS::SSM::Parameter::Value<String>
    Default: REACT_APP_ORCID_REDIRECT_URI

Resources:

  # ===============================
  #  Frontend
  # ===============================

  NVAFrontend:
    Type: AWS::Serverless::Application
    Description: NVA Frontend
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:884807050265:applications/NVA-Frontend
        SemanticVersion: 0.1.28
      Parameters:
        AlmaApiUrl: !Ref AlmaSruHost
        AmazonCognitoDomain: !Ref CognitoAuthenticationDomain
        FrontendDomain: !Ref ApplicationDomain
        BackendDomain: !Ref BackendApiUrl
        DomainCertificateArn: !Ref ApplicationDomainCertificateArn
        CognitoIdentityPoolId: !Ref CognitoIdentityPoolId
        UserPoolId: !Ref CognitoUserPoolId
        UserPoolAppClientId: !Ref CognitoUserPoolAppClientId
        RedirectSignInUrl: !Sub 'https://${ApplicationDomain}'
        RedirectSignOutUrl: !Sub 'https://${ApplicationDomain}/logout'
        OrcidBaseUrl: !Ref OrcidBaseUrl
        OrcidClientID: !Ref OrcidClientID
        OrcidClientSecret: !Ref OrcidClientSecret
        OrcidRedirectUri: !Ref OrcidRedirectUri
