AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for parameters and secrets not set by originating templates and services

Parameters:

  CustomDomain:
    Type: String
    Description: Value for Custom Domain.
    Default: dev.nva.aws.unit.no

  AlmaSruHost:
    Type: String
    Description: Hostname of Alma-SRU service
    Default: bibsys.alma.exlibrisgroup.com/view/sru/47BIBSYS_NETWORK

  ApiDomainCertificateArn:
    Type: String
    Description: ARN for the certificate covering the  ApiDomainName in API Gateway

  ApplicationDomainCertificateArn:
    Type: String
    Description: ARN for the certificate covering the ApplicationDomain

  BareHost:
    Type: String
    Description: Hostname for BARE API
    Default: alfa-a.bibsys.no

  OrcidBaseUrl:
    Type: String
    Description: URL to OrcId service
    Default: https://sandbox.orcid.org

  PublicationsTableStreamArn:
    Type: String
    Description: ARN of PublicationsTableStream

  UserServiceApiSecretArn:
    Type: String
    Description: ARN of secret for UserService

Resources:

  AlmaSruHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname of Alma-SRU service
      Name: AlmaSruHost
      Type: String
      Value: !Ref AlmaSruHost

  ApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname for API Gateway Custom Domain
      Name: ApiDomainName
      Type: String
      Value: !Join [ '.', [ 'api', !Ref CustomDomain ] ]

  ApiDomainCertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN for the certificate covering the API host/domain/API Gateway Custom Domain
      Name: ApiDomainCertificateArn
      Type: String
      Value: !Ref ApiDomainCertificateArn

  ApplicationDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Domainname for the frontend
      Name: ApplicationDomain
      Type: String
      Value: !Join [ '.', [ 'frontend', !Ref CustomDomain ] ]

  ApplicationDomainCertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN for the certificate covering the ApplicationDomain
      Name: ApplicationDomainCertificateArn
      Type: String
      Value: !Ref ApplicationDomainCertificateArn


  BareHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname for BARE API
      Name: BareHost
      Type: String
      Value: !Ref BareHost

  BackendDomainURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: URL for backend API
      Name: BackendApiUrl
      Type: String
      Value: !Join [ '.', [ 'https://api', !Ref CustomDomain ] ]


  OrcidBaseUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: URL to OrcId service
      Name: OrcidBaseUrl
      Type: String
      Value: !Ref OrcidBaseUrl

  CustomDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Value for Custom Domain.
      Name: CustomDomain
      Type: String
      Value: !Ref CustomDomain

  EventBusNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Name of EventBus.
      Name: EventBusName
      Type: String
      Value: default

  EventBusArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of EventBus.
      Name: EventBusArn
      Type: String
      Value: !Sub arn:aws:events:{{AWS::Region}}:{{AWS::Account}}:event-bus/default


