AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for parameters and secrets not set by originating templates and services

Parameters:

  CustomDomain:
    Type: String
    Description: Value for Custom Domain.
    Default: dev.nva.aws.unit.no

  AlmaSruHost:
    Type: String
    Description: Hostname of Alma-SRU service
    Default: bibsys.alma.exlibrisgroup.com/view/sru/47BIBSYS_NETWORK

  ApiDomainCertificateArn:
    Type: String
    Description: ARN for the certificate covering the  ApiDomainName in API Gateway

  ApplicationDomainCertificateArn:
    Type: String
    Description: ARN for the certificate covering the ApplicationDomain

  BareApiKey:
    Type: String
    Description: Key to access BARE API
    NoEcho: true

  BareHost:
    Type: String
    Description: Hostname for BARE API
    Default: alfa-a.bibsys.no

  CognitoFrontendApplicationUrl:
    Type: String
    Description: A base URL for the callbacks for the identity providers.
    Default: 'https://frontend.dev.nva.aws.unit.no'

  CognitoAuthenticationDomainPrefix:
    Type: String
    Description: The prefix for the Cognito domain that hosts the sign-up and sign-in pages for your application.
    Default: nva-stage

  FeideMetadataUrl:
    Type: String
    Description: Link to the the identity provider details.
    Default: 'https://idp-test.feide.no/simplesaml/saml2/idp/metadata.php'

  NVAResourceStorageBucket:
    Type: String
    Description: Name of S3 Bucket storing NVA Resources

  OrcidBaseUrl:
    Type: String
    Description: URL to OrcId service
    Default: https://sandbox.orcid.org

  PublicationsTableStreamArn:
    Type: String
    Description: ARN of PublicationsTableStream

  UserServiceApiSecretArn:
    Type: String
    Description: ARN of secret for UserService

Resources:

  AlmaSruHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname of Alma-SRU service
      Name: AlmaSruHost
      Type: String
      Value: !Ref AlmaSruHost

  ApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname for API Gateway Custom Domain
      Name: ApiDomainName
      Type: String
      Value: !Join [ '.', [ 'api', !Ref CustomDomain ] ]

  ApiDomainCertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN for the certificate covering the API host/domain/API Gateway Custom Domain
      Name: ApiDomainCertificateArn
      Type: String
      Value: !Ref ApiDomainCertificateArn

  ApplicationDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Domainname for the frontend
      Name: ApplicationDomain
      Type: String
      Value: !Join [ '.', [ 'frontend', !Ref CustomDomain ] ]

  ApplicationDomainCertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN for the certificate covering the ApplicationDomain
      Name: ApplicationDomainCertificateArn
      Type: String
      Value: !Ref ApplicationDomainCertificateArn

  BareApiKeyParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Key to access BARE API
      Name: BareApiKey
      SecretString: !Ref BareApiKey

  BareHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname for BARE API
      Name: BareHost
      Type: String
      Value: !Ref BareHost

  BackendDomainURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: URL for backend API
      Name: BackendApiUrl
      Type: String
      Value: !Join [ '.', [ 'https://api', !Ref CustomDomain ] ]

  CognitoAuthenticationDomainPrefixParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The prefix for the Cognito domain that hosts the sign-up and sign-in pages for your application.
      Name: CognitoAuthenticationDomainPrefix
      Type: String
      Value: !Ref CognitoAuthenticationDomainPrefix

  CognitoFrontendApplicationUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: A base URL for the callbacks for the identity providers.
      Name: CognitoFrontendApplicationUrl
      Type: String
        Value: !Ref CognitoFrontendApplicationUrl

  FeideMetadataUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Link to the the identity provider details.
      Name: FeideMetadataUrl
      Type: String
      Value: !Ref FeideMetadataUrl

  NVAResourceStorageBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Name of S3 Bucket storing NVA Resources
      Name: NVAResourceStorageBucket
      Type: String
      Value: !Ref NVAResourceStorageBucket

  OrcidBaseUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: URL to OrcId service
      Name: OrcidBaseUrl
      Type: String
      Value: !Ref OrcidBaseUrl

  PublicationsTableStreamArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of PublicationsTableStream
      Name: PublicationsTableStreamArn
      Type: String
      Value: !Ref PublicationsTableStreamArn

  UserServiceApiSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of secret for UserService
      Name: UserServiceApiSecretArn
      Type: String
      Value: !Ref UserServiceApiSecretArn

  CustomDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Value for Custom Domain.
      Name: CustomDomain
      Type: String
      Value: !Ref CustomDomain

  EventBusNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Name of EventBus.
      Name: EventBusName
      Type: String
      Value: default

  EventBusArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of EventBus.
      Name: EventBusArn
      Type: String
      Value: !Sub arn:aws:events:{{AWS::Region}}:{{AWS::Account}}:event-bus/default


