AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for parameters and secrets not set by originating templates and services

Parameters:

  AlmaSruHost:
    Type: String
    Description: Hostname of Alma-SRU service
    Default: bibsys.alma.exlibrisgroup.com/view/sru/47BIBSYS_NETWORK

  ApiDomainName:
    Type: String
    Description: Hostname for API Gateway Custom Domain
    Default: api.host.nva.aws.unit.no

  ApiDomainCertificateArn:
    Type: String
    Description: ARN for the certificate covering the  ApiDomainName in API Gateway

  ApplicationDomain:
    Type: String
    Description: Domainname for the frontend
    Default: frontend.host.nva.aws.unit.no

  ApplicationDomainCertificateArn:
    Type: String
    Description: ARN for the certificate covering the ApplicationDomain

  BackendApiUrl: # AKA BackendDomainURL, BackendDomain
    Type: String
    Description: URL for backend API
    Default: https://api.host.nva.aws.unit.no

  BareApiKey:
    Type: String
    Description: Key to access BARE API
    NoEcho: true

  BareHost:
    Type: String
    Description: Hostname for BARE API
    Default: alfa-a.bibsys.no

  NVAResourceStorageBucket:
    Type: String
    Description: Name of S3 Bucket storing NVA Resources

  OrcidBaseUrl:
    Type: String
    Description: URL to OrcId service
    Default: https://sandbox.orcid.org

  PublicationsTableStreamArn:
    Type: String
    Description: ARN of PublicationsTableStream

  UserServiceApiSecretArn:
    Type: String
    Description: ARN of secret for UserService

Resources:

  AlmaSruHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname of Alma-SRU service
      Name: AlmaSruHost
      Type: String
      Value: !Ref AlmaSruHost

  ApiDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname for API Gateway Custom Domain
      Name: ApiDomainName
      Type: String
      Value: !Ref ApiDomainName

  ApiDomainCertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN for the certificate covering the API host/domain/API Gateway Custom Domain
      Name: ApiDomainCertificateArn
      Type: String
      Value: !Ref ApiDomainCertificateArn

  ApplicationDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Domainname for the frontend
      Name: ApplicationDomain
      Type: String
      Value: !Ref ApplicationDomain

  ApplicationDomainCertificateArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN for the certificate covering the ApplicationDomain
      Name: ApplicationDomainCertificateArn
      Type: String
      Value: !Ref ApplicationDomainCertificateArn

  BareApiKeyParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Key to access BARE API
      Name: BareApiKey
      SecretString: !Ref BareApiKey

  BareHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Hostname for BARE API
      Name: BareHost
      Type: String
      Value: !Ref BareHost

  BackendDomainURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: URL for backend API
      Name: BackendApiUrl
      Type: String
      Value: !Ref BackendApiUrl

  NVAResourceStorageBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Name of S3 Bucket storing NVA Resources
      Name: NVAResourceStorageBucket
      Type: String
      Value: !Ref NVAResourceStorageBucket

  OrcidBaseUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: URL to OrcId service
      Name: OrcidBaseUrl
      Type: String
      Value: !Ref OrcidBaseUrl

  PublicationsTableStreamArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of PublicationsTableStream
      Name: PublicationsTableStreamArn
      Type: String
      Value: !Ref PublicationsTableStreamArn

  UserServiceApiSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: ARN of secret for UserService
      Name: UserServiceApiSecretArn
      Type: String
      Value: !Ref UserServiceApiSecretArn

